In [3]:
import tensorflow as tf
import numpy as np
from q1_softmax import *

%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [4]:
test_softmax_basic()
test_cross_entropy_loss_basic()

Running basic tests...
Basic (non-exhaustive) softmax tests pass

Basic (non-exhaustive) cross-entropy tests pass



In [5]:
from q1_classifier import *
test_SoftmaxModel()

Epoch 0: loss = 63.15 (0.022 sec)
Epoch 1: loss = 21.69 (0.011 sec)
Epoch 2: loss = 11.66 (0.010 sec)
Epoch 3: loss = 7.79 (0.010 sec)
Epoch 4: loss = 5.80 (0.010 sec)
Epoch 5: loss = 4.61 (0.010 sec)
Epoch 6: loss = 3.82 (0.010 sec)
Epoch 7: loss = 3.25 (0.010 sec)
Epoch 8: loss = 2.83 (0.011 sec)
Epoch 9: loss = 2.51 (0.010 sec)
Epoch 10: loss = 2.25 (0.010 sec)
Epoch 11: loss = 2.04 (0.010 sec)
Epoch 12: loss = 1.86 (0.010 sec)
Epoch 13: loss = 1.71 (0.010 sec)
Epoch 14: loss = 1.59 (0.010 sec)
Epoch 15: loss = 1.48 (0.010 sec)
Epoch 16: loss = 1.38 (0.011 sec)
Epoch 17: loss = 1.30 (0.011 sec)
Epoch 18: loss = 1.23 (0.015 sec)
Epoch 19: loss = 1.16 (0.016 sec)
Epoch 20: loss = 1.10 (0.021 sec)
Epoch 21: loss = 1.05 (0.026 sec)
Epoch 22: loss = 1.00 (0.012 sec)
Epoch 23: loss = 0.95 (0.010 sec)
Epoch 24: loss = 0.91 (0.010 sec)
Epoch 25: loss = 0.88 (0.011 sec)
Epoch 26: loss = 0.84 (0.011 sec)
Epoch 27: loss = 0.81 (0.012 sec)
Epoch 28: loss = 0.78 (0.010 sec)
Epoch 29: loss = 0.75

In [6]:
from q2_initialization import *
test_initialization_basic()

Running basic tests...
Basic (non-exhaustive) Xavier initialization tests pass



In [7]:
test_initialization()

Running your tests...
Xavier initialization tests pass



In [38]:
from q2_NER import *
test_NER()


Epoch 0
Training loss: 0.526823639873639875
Training acc: 0.864611213971
Validation loss: 0.337512075901

[[42308    62    49   111   229]
 [  628  1188    34   148    96]
 [  654    44   527    19    24]
 [ 1155   168    37   498   234]
 [ 1018    45     3    73  2010]]
Tag: O - P 0.9245 / R 0.9895
Tag: LOC - P 0.7883 / R 0.5673
Tag: MISC - P 0.8108 / R 0.4156
Tag: ORG - P 0.5866 / R 0.2380
Tag: PER - P 0.7752 / R 0.6383
Total time: 34.7864489555
Epoch 1
Training loss: 0.475047826767826767
Training acc: 0.878101963943
Validation loss: 0.328820586205

[[42010   200    52   186   311]
 [  396  1372    43   178   105]
 [  577    42   573    37    39]
 [  976   184    49   659   224]
 [  718    59     5   264  2103]]
Tag: O - P 0.9403 / R 0.9825
Tag: LOC - P 0.7388 / R 0.6552
Tag: MISC - P 0.7936 / R 0.4519
Tag: ORG - P 0.4977 / R 0.3150
Tag: PER - P 0.7559 / R 0.6678
Total time: 32.914659977
Epoch 2
Training loss: 0.470435202122202122
Training acc: 0.878897559682
Validation loss: 0.32657