In [2]:
import tensorflow as tf
import numpy as np

In [31]:
sess = tf.Session()

w = tf.Variable(tf.random_normal((4,3)))
b = tf.Variable(tf.random_normal([4,3]))

sess.run(tf.global_variables_initializer())

b = tf.reshape(b, [3,4])

wb = tf.matmul(w,b)

print sess.run(wb)

[[-2.08459783  2.5226357  -0.40043133 -0.32199419]
 [ 1.02889991  0.14091396  1.01134872  0.30804074]
 [ 0.60854661 -0.86278868 -1.02646148 -0.4713909 ]
 [-4.00863552  4.98334885 -0.46208158 -0.48612881]]


In [ ]:
x = tf.constant([35, 40, 45], name='x')
y = tf.Variable(x + 5, name='y')


with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print session.run(y)

In [32]:
x = tf.Variable(0, name='x')

session = tf.InteractiveSession()

for i in range(5):
    tf.global_variables_initializer().run()
    x += np.random.randint(1000)
    x /= i+1
    print x.eval()
    
session.close()

477
551
290
280
141


In [38]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)


Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [60]:
sess = tf.Session()
n_samples = tf.constant(10)
n_features = tf.constant(5)

x = tf.Variable(tf.random_normal((n_samples,n_features)))
y = tf.Variable(tf.random_normal((n_samples,n_features)))

sess.run(tf.global_variables_initializer())

probs = tf.exp(x - tf.reduce_max(x, axis=1, keep_dims=True))
probs /= tf.reduce_sum(probs, axis=1, keep_dims=True)

p_c = probs[, tf.gather(y)]
      
"""
loss = -tf.reduce_sum(tf.log(probs[np.arange(n_samples), y])) / n_samples
dx = probs.copy()
dx[np.arange(n_samples), y] -= 1
dx /= n_samples

#print probs


"""

SyntaxError: invalid syntax (<ipython-input-60-2ac4f5f234a6>, line 13)